name: CI/CD Pipeline 

on:
  workflow_dispatch:

jobs:
  quality-checks:
    name: Run Lint & Tests
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      # Backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest
      
      - name: Run tests
        working-directory: ./backend
        run: pytest

      # Frontend
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Frontend - Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Frontend - Test
        working-directory: ./frontend
        run: npm test -- --watchAll=false

  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Backend Image
      - name: Build & Push Backend Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: dev-${{ github.sha }}
        working-directory: ./backend
        run: |
          docker build -t $ECR_REGISTRY/devops-backend:$IMAGE_TAG .
          docker push $ECR_REGISTRY/devops-backend:$IMAGE_TAG
          echo "BACKEND_IMAGE=$ECR_REGISTRY/devops-backend:$IMAGE_TAG" >> $GITHUB_ENV

      # Frontend Image
      - name: Build & Push Frontend Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: dev-${{ github.sha }}
        working-directory: ./frontend
        run: |
          docker build -t $ECR_REGISTRY/devops-frontend:$IMAGE_TAG .
          docker push $ECR_REGISTRY/devops-frontend:$IMAGE_TAG
          echo "FRONTEND_IMAGE=$ECR_REGISTRY/devops-frontend:$IMAGE_TAG" >> $GITHUB_ENV

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: ./docker-compose.yml
          target: ~/app/docker-compose.yml

      - name: Deploy Docker Containers
        uses: appleboy/ssh-action@v1
        env:
          BACKEND_IMAGE: ${{ env.BACKEND_IMAGE }}
          FRONTEND_IMAGE: ${{ env.FRONTEND_IMAGE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          envs: BACKEND_IMAGE,FRONTEND_IMAGE
          script: |
            cd ~/app
            docker pull $BACKEND_IMAGE
            docker pull $FRONTEND_IMAGE
            docker-compose down
            docker-compose up -d
